apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tuskr-controller-binding
subjects:
  - kind: ServiceAccount
    name: tuskr-controller-sa
    namespace: tuskr
roleRef:
  kind: ClusterRole
  name: tuskr-controller
  apiGroup: rbac.authorization.k8s.io
