apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jobtemplates.tuskr.io
spec:
  group: tuskr.io
  names:
    kind: JobTemplate
    listKind: JobTemplateList
    plural: jobtemplates
    singular: jobtemplate
  scope: Namespaced
  # We will disable the global "preserveUnknownFields" so that we can
  # opt into preservation only where we need it
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - jobSpec
              properties:
                jobSpec:
                  type: object
                  required:
                    - template
                  properties:
                    template:
                      type: object
                      # *** HERE: preserve everything under .template! ***
                      x-kubernetes-preserve-unknown-fields: true
                      description: |
                        This lets you supply _any_ valid PodTemplateSpec fields:
                        containers, initContainers, volumes, env, envFrom, volumeMounts, securityContext,
                        shareProcessNamespace, affinity, tolerations, etc.
