apiVersion: apps/v1
kind: Deployment
metadata:
  name: tuskr-controller
  labels:
    app: tuskr-controller
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tuskr-controller
  template:
    metadata:
      labels:
        app: tuskr-controller
    spec:
      serviceAccountName: tuskr-controller-sa
      containers:
      - name: tuskr-controller
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # This assumes your code runs with: python -m kopf or python path
        # If you prefer your main.py approach, adjust accordingly:
        command: ["python"]
        args: ["-m", "kopf", "run", "/home/user/app/tuskr_controller.py"]
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
